name: pr_functions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * MON'
  pull_request:
    paths:
    - ".github/workflows/pr_functions.yml"
    - "functions/*.tf"

jobs:
  on-pull-request:
    name: terraform
    runs-on: ubuntu-latest

    # composite 内の run に continue-on-error が付けられないので外で
    continue-on-error: true
    strategy:
      # matrix のジョブのどれかがエラーになっても他のジョブをキャンセルしない（false）
      fail-fast: false
      matrix:
        dir:
        - "functions"

    steps:
    - uses: actions/checkout@master

    - uses: ./.github/actions/terraform
      with:
        terraform_version: 1.1.x
        secrets_github_token: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ${{ matrix.dir }}
      if: always()

